services:
  - type: web
    name: agam-frontend
    env: docker
    plan: free
    rootDir: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: agam-backend
          property: host
        sync: false

  - type: web
    name: agam-backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: agam.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost
      - key: DEBUG
        value: false
      - key: PORT
        value: 8000
      - key: POSTGRES_DB
        fromDatabase:
          name: agam-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: agam-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: agam-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: agam-db
          property: host
      - key: POSTGRES_PORT
        value: 5432

databases:
  - name: agam-db
    plan: free
