services:
  - type: web
    name: agam-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: agam-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn agam.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: agam.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: 0.0.0.0,localhost
