services:
  - type: web
    name: agam-frontend
    env: docker
    plan: free
    rootDir: frontend           # 👈 add this
    dockerfilePath: Dockerfile # 👈 remove ./frontend/ prefix
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: agam-backend
    env: docker
    plan: free
    rootDir: backend            # 👈 add this
    dockerfilePath: Dockerfile # 👈 remove ./backend/ prefix
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: agam.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: 0.0.0.0,localhost
